# Generated by Django 4.2.30 on 2026-05-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("estimator", "Estimator"),
                    ("detailing", "Detailing / JF"),
                    ("readonly", "Read-Only"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
