# Generated by Django 4.2.30 on 2026-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="editing_project_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="editing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
