# Generated by Django 4.2.30 on 2026-06-17 08:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_editing_project_id_user_editing_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=accounts.models.get_default_modules),
        ),
    ]
