# Generated by Django 4.2.30 on 2026-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='employee', max_length=100),
        ),
    ]
