# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISCSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
                ('bf', models.DecimalField(decimal_places=4, help_text='Flange width (in)', max_digits=8)),
                ('tf', models.DecimalField(decimal_places=4, help_text='Flange thickness (in)', max_digits=8)),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['label'], name='field_momen_label_7d383c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldMomentConnTakeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_moment_conn_takeoff', to='projects.project')),
            ],
            options={
                'verbose_name': 'Field Moment Connection Takeoff',
            },
        ),
        migrations.CreateModel(
            name='FieldMomentConnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('aisc_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fmc_lines', to='field_moment_conn.aiscsection')),
                ('takeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='field_moment_conn.fieldmomentconntakeoff')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
