# Generated by Django 4.2.13 on 2026-05-25 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Estimator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initials", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["initials"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyBidGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ]
                    ),
                ),
                (
                    "goal",
                    models.DecimalField(
                        decimal_places=2, default=2000000, max_digits=15
                    ),
                ),
            ],
            options={
                "ordering": ["year", "month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="RFQMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_no",
                    models.CharField(
                        help_text="Format: YY-MM-SEQ (e.g. 23-06-05). Rebids: 23-06-05R or 23-06-05R1",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Quote No must follow format YY-MM-SEQ (e.g. 23-06-05) or with rebid suffix (e.g. 23-06-05R1)",
                                regex="^\\d{2}-\\d{2}-\\d{2,3}(R\\d?)?$",
                            )
                        ],
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Budget", "Budget"),
                            ("Final", "Final"),
                            ("Rebid", "Rebid"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "bid_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("project_name", models.CharField(max_length=300)),
                ("project_comments", models.TextField(blank=True, default="")),
                ("bid_due_date", models.DateField(blank=True, null=True)),
                ("bid_due_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "distance_travel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance/travel time in hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "aisc_fab",
                    models.BooleanField(default=False, verbose_name="AISC Fabrication"),
                ),
                (
                    "aisc_erect",
                    models.BooleanField(default=False, verbose_name="AISC Erection"),
                ),
                (
                    "domestic_steel",
                    models.BooleanField(default=False, verbose_name="Domestic Steel"),
                ),
                (
                    "leed_project",
                    models.BooleanField(default=False, verbose_name="LEED Project"),
                ),
                (
                    "minority_participation",
                    models.BooleanField(
                        default=False, verbose_name="Minority Participation"
                    ),
                ),
                (
                    "prevailing_wage",
                    models.BooleanField(default=False, verbose_name="Prevailing Wage"),
                ),
                (
                    "ccip_ocip",
                    models.BooleanField(default=False, verbose_name="CCIP/OCIP"),
                ),
                ("bonded", models.BooleanField(default=False, verbose_name="Bonded")),
                ("paint", models.BooleanField(default=False, verbose_name="Paint")),
                (
                    "galvanised",
                    models.BooleanField(default=False, verbose_name="Galvanised"),
                ),
                (
                    "professional_engineer",
                    models.BooleanField(
                        default=False, verbose_name="Professional Engineer"
                    ),
                ),
                (
                    "third_party_inspection",
                    models.BooleanField(
                        default=False, verbose_name="3rd Party Inspection"
                    ),
                ),
                (
                    "tax_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Taxable", "Taxable"),
                            ("Exempt", "Exempt"),
                            ("Partial", "Partial Exempt"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "decision_to_bid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("NoBid", "No Bid"),
                            ("Bid", "Bid"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "outsourced_estimator",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "sent_to_jd",
                    models.BooleanField(default=False, verbose_name="Sent to J&D"),
                ),
                (
                    "sent_to_detailing",
                    models.BooleanField(
                        default=False, verbose_name="Sent to Detailing"
                    ),
                ),
                (
                    "sent_to_erection",
                    models.BooleanField(default=False, verbose_name="Sent to Erection"),
                ),
                (
                    "est_sqft_ton",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Est. Sq-Ft / Tons",
                    ),
                ),
                (
                    "price_structure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_erection",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_misc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_misc_erection",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "bid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Col AL — used in dashboard aggregations",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "quoted_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Col AM — used in dashboard aggregations",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "ton_steel",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "ton_joist",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("num_main_structural_pcs", models.IntegerField(blank=True, null=True)),
                (
                    "sq_ft_structural",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "struct_fab_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "struct_fab_start_month",
                    models.DateField(
                        blank=True,
                        help_text="Store as first day of the month (YYYY-MM-01)",
                        null=True,
                    ),
                ),
                (
                    "struct_fab_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "misc_fab_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("misc_fab_start_month", models.DateField(blank=True, null=True)),
                (
                    "misc_fab_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "struct_erect_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("struct_erect_start_month", models.DateField(blank=True, null=True)),
                (
                    "struct_erect_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "misc_erect_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("misc_erect_start_month", models.DateField(blank=True, null=True)),
                (
                    "misc_erect_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "estimating_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("quote_date", models.DateField(blank=True, null=True)),
                (
                    "won_lost",
                    models.CharField(
                        choices=[
                            ("Won", "Won"),
                            ("Lost", "Lost"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("follow_up_notes", models.TextField(blank=True, default="")),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "awarded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sfe_job_no",
                    models.IntegerField(
                        blank=True,
                        help_text="SFE internal job number (e.g. 22003). Required when Won.",
                        null=True,
                        unique=True,
                    ),
                ),
                ("awarded_job_date", models.DateField(blank=True, null=True)),
                ("contract_executed_date", models.DateField(blank=True, null=True)),
                (
                    "fabrication_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Entered by Detailing / JF role",
                        null=True,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs",
                        to="rfq.customer",
                    ),
                ),
                (
                    "primary_estimator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs",
                        to="rfq.estimator",
                    ),
                ),
            ],
            options={
                "db_table": "rfq_master",
                "ordering": ["-bid_due_date", "-id"],
                "indexes": [
                    models.Index(fields=["quote_date"], name="idx_rfq_quote_date"),
                    models.Index(
                        fields=["awarded_job_date"], name="idx_rfq_awarded_date"
                    ),
                    models.Index(fields=["won_lost"], name="idx_rfq_won_lost"),
                    models.Index(fields=["customer"], name="idx_rfq_customer"),
                    models.Index(fields=["sfe_job_no"], name="idx_rfq_sfe_job_no"),
                    models.Index(fields=["bid_due_date"], name="idx_rfq_bid_due_date"),
                    models.Index(fields=["deleted_at"], name="idx_rfq_deleted_at"),
                ],
            },
        ),
    ]
