# Generated by Django 4.2.30 on 2026-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmaster',
            name='scope_of_work',
            field=models.CharField(blank=True, choices=[('Detailing', 'Detailing'), ('Fabrication', 'Fabrication'), ('Erection', 'Erection')], max_length=50, null=True),
        ),
    ]
