# Generated by Django 4.2.30 on 2026-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_rfqmaster_scope_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmaster',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
