# Generated by Django 4.2.30 on 2026-06-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_estimation_data'),
        ('rfq', '0003_rfqmaster_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqmaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='projects.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
