# Generated by Django 4.2.30 on 2026-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_alter_rfqmaster_customer_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rfq_systemsetting',
            },
        ),
        migrations.AlterField(
            model_name='rfqmaster',
            name='scope_of_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
