# Generated by Django 4.2.30 on 2026-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0006_systemsetting_alter_rfqmaster_scope_of_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfqmaster',
            options={'ordering': ['-quote_no', '-id']},
        ),
    ]
