# Generated by Django 4.2.30 on 2026-08-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_alter_rfqmaster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteWorkflow',
            fields=[
                ('quote_id', models.CharField(help_text='Unique Quote Reference / Quote No', max_length=100, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('sender', models.CharField(blank=True, default='', help_text='Original customer email', max_length=255)),
                ('status', models.CharField(choices=[('Forwarded', 'Forwarded'), ('Partially Replied', 'Partially Replied'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Forwarded', max_length=50)),
                ('estimator_email', models.CharField(blank=True, default='', max_length=255)),
                ('estimator_replied', models.BooleanField(default=False)),
                ('estimator_reply_body', models.TextField(blank=True, null=True)),
                ('estimator_replied_at', models.DateTimeField(blank=True, null=True)),
                ('detailer_email', models.CharField(blank=True, default='', max_length=255)),
                ('detailer_replied', models.BooleanField(default=False)),
                ('detailer_reply_body', models.TextField(blank=True, null=True)),
                ('detailer_replied_at', models.DateTimeField(blank=True, null=True)),
                ('combined_body', models.TextField(blank=True, null=True)),
                ('sent_to_customer_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_workflows', to='rfq.rfqmaster')),
            ],
            options={
                'db_table': 'rfq_quote_workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
