# Generated by Django 4.2.30 on 2026-08-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_quoteworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteworkflow',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_workflows', to='rfq.rfqmaster'),
        ),
    ]
