# Generated by Django 4.2.30 on 2026-05-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="client",
            new_name="customer_name",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="end_date",
            new_name="erection_date",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="manager",
            new_name="project_manager_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.AddField(
            model_name="project",
            name="detailer_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="manhour_ton",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_manhours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="project",
            name="total_ton",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="StructuralSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_no", models.CharField(blank=True, max_length=50)),
                (
                    "tons",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("item_description", models.TextField(blank=True)),
                ("scheduled_ofa_date", models.DateField(blank=True, null=True)),
                ("actual_ofa_date", models.DateField(blank=True, null=True)),
                ("scheduled_bfa_date", models.DateField(blank=True, null=True)),
                ("actual_bfa_date", models.DateField(blank=True, null=True)),
                (
                    "scheduled_field_measure_date",
                    models.DateField(blank=True, null=True),
                ),
                ("rts_date", models.DateField(blank=True, null=True)),
                ("num_days", models.IntegerField(default=0)),
                ("shop_lead_time_weeks", models.IntegerField(default=0)),
                ("scheduled_erection_date", models.DateField(blank=True, null=True)),
                (
                    "shop_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "field_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status_location", models.CharField(blank=True, max_length=200)),
                ("material_finish", models.CharField(blank=True, max_length=200)),
                ("detailer_vendor", models.CharField(blank=True, max_length=200)),
                ("dwg_status", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "structural_schedules",
            },
        ),
    ]
