# Generated by Django 4.2.30 on 2026-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='pm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='detailer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='job_number',
            field=models.CharField(default='TBD', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='mhs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='mhs_per_ton',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_up_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tons',
            field=models.FloatField(default=0),
        ),
    ]
