# Generated by Django 4.2.30 on 2026-05-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detailer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manhour_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_manhours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='total_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='StructuralScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.CharField(max_length=50)),
                ('tons', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.CharField(max_length=500)),
                ('scheduled_ofa_date', models.DateField(blank=True, null=True)),
                ('actual_ofa_date', models.DateField(blank=True, null=True)),
                ('scheduled_bfa_date', models.DateField(blank=True, null=True)),
                ('actual_bfa_date', models.DateField(blank=True, null=True)),
                ('scheduled_field_measure_date', models.DateField(blank=True, null=True)),
                ('rts_date', models.DateField(blank=True, null=True)),
                ('num_days', models.IntegerField(default=0)),
                ('shop_lead_time_weeks', models.IntegerField(default=0)),
                ('scheduled_erection_date', models.DateField(blank=True, null=True)),
                ('shop_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('field_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('material_finish', models.CharField(blank=True, max_length=200)),
                ('detailer_vendor', models.CharField(blank=True, max_length=200)),
                ('dwg_status', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_schedules', to='projects.project')),
            ],
            options={
                'db_table': 'structural_schedule_items',
                'ordering': ['seq_no'],
            },
        ),
    ]
