# Generated by Django 4.2.30 on 2026-05-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_client_project_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuralschedule",
            name="field_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="num_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="shop_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="shop_lead_time_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
