# Generated by Django 4.2.30 on 2026-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_structuralschedule_field_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuralschedule",
            name="field_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="item_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="num_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="shop_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="shop_lead_time_weeks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="structuralschedule",
            name="tons",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
