# Generated by Django 4.2.30 on 2026-05-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='erection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
