# Generated by Django 4.2.30 on 2026-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_structuralschedule_field_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structuralschedule",
            name="status_location",
        ),
        migrations.AddField(
            model_name="structuralschedule",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="structuralschedule",
            name="status",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
