# Generated by Django 4.2.30 on 2026-05-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_erection_date_alter_project_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
