# Generated by Django 4.2.30 on 2026-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_budget_remove_project_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralscheduleitem',
            old_name='field_hours',
            new_name='actual_field_hours',
        ),
        migrations.RenameField(
            model_name='structuralscheduleitem',
            old_name='shop_hours',
            new_name='actual_shop_hours',
        ),
        migrations.RemoveField(
            model_name='structuralscheduleitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='structuralscheduleitem',
            name='material_finish',
        ),
        migrations.RemoveField(
            model_name='structuralscheduleitem',
            name='num_days',
        ),
        migrations.RemoveField(
            model_name='structuralscheduleitem',
            name='status',
        ),
        migrations.AddField(
            model_name='structuralscheduleitem',
            name='budget_field_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='structuralscheduleitem',
            name='budget_shop_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
