# Generated by Django 4.2.30 on 2026-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_field_hours_structuralscheduleitem_actual_field_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralscheduleitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
