# Generated by Django 4.2.30 on 2026-05-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_structuralscheduleitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.CharField(blank=True, max_length=50)),
                ('material_size', models.CharField(blank=True, max_length=200)),
                ('dimension', models.CharField(blank=True, max_length=200)),
                ('machine', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_details', to='projects.structuralscheduleitem')),
            ],
            options={
                'db_table': 'fabrication_details',
            },
        ),
    ]
