# Generated by Django 4.2.30 on 2026-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_fabricationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralscheduleitem',
            name='fabrication_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='FabricationDetail',
        ),
    ]
