# Generated by Django 4.2.30 on 2026-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_customer_detailer_detailercontact_customercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuralscheduleitem",
            name="tracking_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
