# Generated by Django 4.2.30 on 2026-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_structuralscheduleitem_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Yet to Complete', 'Yet to Complete'), ('Completed', 'Completed')], default='Yet to Complete', max_length=20),
        ),
    ]
