# Generated by Django 4.2.30 on 2026-05-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("In Progress", "In Progress"),
                    ("Yet to Complete", "Yet to Complete"),
                    ("Completed", "Completed"),
                ],
                default="Yet to Complete",
                max_length=20,
            ),
        ),
    ]
