# Generated by Django 4.2.30 on 2026-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralscheduleitem',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
