# Generated by Django 4.2.30 on 2026-05-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_structuralscheduleitem_ship_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="schedule_field_measure_required",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AddField(
            model_name="project",
            name="shop_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
