# Generated by Django 4.2.30 on 2026-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_schedule_field_measure_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="schedule_field_measure_required",
            field=models.CharField(default="Yes", max_length=10),
        ),
    ]
