# Generated by Django 4.2.30 on 2026-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_project_schedule_field_measure_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="steel_budget_worksheet",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
