# Generated by Django 4.2.30 on 2026-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_project_steel_budget_worksheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("In Progress", "In Progress"),
                    ("Yet to Start", "Yet to Start"),
                    ("Completed", "Completed"),
                ],
                default="Yet to Start",
                max_length=20,
            ),
        ),
    ]
