# Generated by Django 4.2.30 on 2026-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuralscheduleitem",
            name="actual_rts_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="structuralscheduleitem",
            name="actual_ship_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
