# Generated by Django 4.2.30 on 2026-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_structuralscheduleitem_actual_rts_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimation_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
