# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('preparer_name', models.CharField(max_length=200)),
                ('prevailing_wage', models.BooleanField(default=False)),
                ('out_of_town', models.BooleanField(default=False)),
                ('data_snapshot', models.JSONField()),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleOfValuesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('50', 'Bond'), ('100', 'Drawings'), ('200', 'Steel'), ('300', 'Joist'), ('400', 'Deck'), ('500', 'Miscellaneous Metals'), ('600', 'Erection')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sov_lines', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
    ]
