# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscMetalsEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misc_metals_estimate', to='projects.project')),
            ],
            options={
                'verbose_name': 'Misc Metals Estimate',
            },
        ),
        migrations.CreateModel(
            name='MiscMetalsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grating', 'Grating'), ('ladder', 'Ladders'), ('platform', 'Platforms'), ('safety_cage', 'Safety Cages'), ('bollard', 'Bollards'), ('hatch_frame', 'Hatch Frames'), ('railing', 'Railings'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shop_rate', models.DecimalField(decimal_places=4, default=0, help_text='Shop hrs per unit', max_digits=10)),
                ('field_rate', models.DecimalField(decimal_places=4, default=0, help_text='Field hrs per unit', max_digits=10)),
                ('material_rate', models.DecimalField(decimal_places=4, default=0, help_text='Material $ per unit', max_digits=10)),
                ('is_galvanized', models.BooleanField(default=False)),
                ('is_anodized', models.BooleanField(default=False)),
                ('is_subcontract', models.BooleanField(default=False)),
                ('subcontract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='misc_metals.miscmetalsestimate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StairFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stair_type', models.CharField(choices=[('picket_rail', 'Stair w/ Picket Rail (MC12×10.6)'), ('mesh_rail', 'Stair w/ Mesh Rail (MC12×10.6)'), ('heavy_rail', 'Stair w/ Rail Heavy (MC12×20.7)'), ('ts_rail', 'Stair w/ Rail TS (TS12×2×1/4)')], default='picket_rail', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('num_risers', models.IntegerField(default=0)),
                ('lf_picket', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lf_mesh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lf_grabrail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lf_wallrail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('num_landings', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stair_flights', to='misc_metals.miscmetalsestimate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
