# Generated by Django 5.1.15 on 2026-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc_metals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscmetalsitem",
            name="is_powder_coated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="miscmetalsitem",
            name="unit_weight",
            field=models.DecimalField(
                decimal_places=4, default=0, help_text="Lbs per unit", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="stairflight",
            name="stair_type",
            field=models.CharField(
                choices=[
                    ("picket_rail", "Stair w/ Picket Rail (MC12×10.6)"),
                    ("mesh_rail", "Stair w/ Mesh Rail (MC12×10.6)"),
                    ("heavy_rail", "Stair w/ Rail Heavy (MC12×20.7)"),
                    ("ts_rail", "Stair w/ Rail TS (TS12×2×1/4)"),
                    ("mesh_heavy_rail", "Stair w/ Mesh Rail Heavy (MC12×20.7)"),
                ],
                default="picket_rail",
                max_length=20,
            ),
        ),
    ]
