# Generated by Django 4.2.30 on 2026-05-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerCode', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Domestic', 'Domestic'), ('Overseas', 'Overseas')], default='Domestic', max_length=20)),
                ('customerEmail', models.JSONField(blank=True, default=list)),
                ('invoiceEmail', models.JSONField(blank=True, default=list)),
                ('billingAddress', models.TextField()),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('paymentNormsDays', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('einNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('bankAccNo', models.CharField(blank=True, max_length=50, null=True)),
                ('w9Form', models.FileField(blank=True, null=True, upload_to='w9_forms/')),
                ('contactPersons', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
