# Generated by Django 6.0.5 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BidSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_steel_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mill_steel_price_per_lb', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('warehouse_steel_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warehouse_steel_price_per_lb', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('bolt_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paint_gallons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('galv_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('joist_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deck_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shop_fab_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('draft_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('draft_sub_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shop_subcontract_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bid Summary',
                'verbose_name_plural': 'Bid Summaries',
            },
        ),
        migrations.CreateModel(
            name='ShopLaborLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
