# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bid_summary', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsummary',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_summary', to='projects.project'),
        ),
        migrations.AddField(
            model_name='bidmaterialline',
            name='bid_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='bid_summary.bidsummary'),
        ),
        migrations.AddField(
            model_name='shoplaborline',
            name='bid_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_lines', to='bid_summary.bidsummary'),
        ),
    ]
