# Generated by Django 5.1.15 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid_summary", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidsummary",
            name="freight_galv_hours_each",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="freight_galv_trucks",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="freight_out_hours_each",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="freight_out_trucks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
