# Generated by Django 5.1.15 on 2026-06-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid_summary", "0003_bidsummary_freight_galv_hours_each_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidsummary",
            name="mill_steel_price_per_lb",
        ),
        migrations.RemoveField(
            model_name="bidsummary",
            name="warehouse_steel_price_per_lb",
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="mill_steel_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="warehouse_steel_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
