# Generated by Django 5.1.15 on 2026-06-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid_summary", "0004_remove_bidsummary_mill_steel_price_per_lb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidsummary",
            name="budget_pricing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="joist_deck_tons",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="leed_data",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="material_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="misc_bid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="misc_metals",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="osha_posts_lf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="pe_stamp_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="safety_ccip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="steel_on_site",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bidsummary",
            name="sublet_erection",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
