# Generated by Django 4.2.30 on 2026-05-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_client_project_customer_and_more'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='title',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='status',
        ),
        migrations.AddField(
            model_name='milestone',
            name='actual_bfa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='actual_ofa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='column1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='milestone',
            name='detailer_vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='milestone',
            name='dwg_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='milestone',
            name='field_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='material_finish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='milestone',
            name='rts_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='scheduled_bfa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='scheduled_field_measure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='scheduled_ofa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='scheduled_start_of_erection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='seq_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='milestone',
            name='shop_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='shop_lead_time_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tons',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project'),
        ),
    ]
