# Generated by Django 4.2.30 on 2026-05-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_rename_title_milestone_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='column1',
            new_name='days',
        ),
    ]
