# Generated by Django 4.2.30 on 2026-08-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_instructions', models.TextField(blank=True, default='', help_text='Additive persona/tone/instructions. Prepended to (never replaces) the mandatory operating rules.')),
                ('enabled_tools', models.JSONField(blank=True, default=None, help_text='List of enabled tool names. NULL means all tools are enabled.', null=True)),
                ('model_override', models.CharField(blank=True, default='', help_text='Overrides OLLAMA_MODEL env setting when non-empty.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
