# Generated by Django 4.2.30 on 2026-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_agentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Dense embedding vector (list of floats) for semantic retrieval. NULL until computed by the ingestion pipeline or a backfill pass.', null=True),
        ),
    ]
