# Generated by Django 4.2.30 on 2026-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_knowledgechunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 of the last-ingested text, used by generate_app_knowledge to skip re-embedding when nothing changed.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='manual', help_text="'generated' documents are produced by generate_app_knowledge from live code introspection.", max_length=20),
        ),
    ]
