# Generated by Django 6.0.5 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref', models.CharField(max_length=100)),
                ('detailer', models.CharField(blank=True, max_length=200)),
                ('mat_ordered', models.BooleanField(default=False)),
                ('erected', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_ref'],
            },
        ),
    ]
