# Generated by Django 4.2.30 on 2026-05-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0016_alter_project_schedule_field_measure_required'),
        ('employees', '0002_employee_dob_employee_gender_employee_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=300)),
                ('project_comments', models.TextField(blank=True, null=True)),
                ('bid_due_date', models.DateField(blank=True, null=True)),
                ('bid_due_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('aisc_fab_req', models.CharField(default='No', max_length=20)),
                ('aisc_erect_req', models.CharField(default='No', max_length=20)),
                ('decision_to_bid', models.CharField(default='TBD', max_length=20)),
                ('sent_to_jd', models.DateField(blank=True, null=True)),
                ('sent_to_detailing', models.DateField(blank=True, null=True)),
                ('sent_to_erection', models.DateField(blank=True, null=True)),
                ('est_sqft_ton', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('sfe_job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('awarded_job_no_date', models.DateField(blank=True, null=True)),
                ('contract_executed_date', models.DateField(blank=True, null=True)),
                ('price_structure', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price_struc_erection', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price_misc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price_misc_erection', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quoted_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ton_steel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ton_joist', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('main_structural_pcs', models.IntegerField(default=0)),
                ('sqft_structural', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('struct_fab_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('struct_fab_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('struct_fab_duration', models.IntegerField(default=0)),
                ('misc_fab_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('misc_fab_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('misc_fab_duration', models.IntegerField(default=0)),
                ('struct_erect_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('struct_erect_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('struct_erect_duration', models.IntegerField(default=0)),
                ('misc_erect_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('misc_erect_start_month', models.CharField(blank=True, max_length=50, null=True)),
                ('misc_erect_duration', models.IntegerField(default=0)),
                ('estimating_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('won_lost', models.CharField(default='Pending', max_length=50)),
                ('estimator_followup_notes', models.TextField(blank=True, null=True)),
                ('estimator_followup_date', models.DateField(blank=True, null=True)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fab_start_date', models.DateField(blank=True, null=True)),
                ('total_tonnage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('struct_pcs_per_ton', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('struct_ton_per_sqft_no_joist', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('struct_ton_per_sqft_with_joist', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('struct_cost_per_ton', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('struct_erect_cost_per_ton', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('struct_cost_per_sqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('struct_erect_cost_per_sqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('struct_fab_end_month', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_monthly_struct_fab_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('misc_fab_end_month', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_monthly_misc_fab_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('struct_erect_end_month', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_monthly_struct_erect_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('misc_erect_end_month', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_monthly_misc_erect_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_enquiries', to='projects.customer')),
                ('primary_estimator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_enquiries', to='employees.employee')),
            ],
            options={
                'db_table': 'bid_enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
