# Generated by Django 4.2.30 on 2026-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidenquiry',
            name='scope_of_work',
            field=models.CharField(blank=True, choices=[('Fabrication', 'Fabrication'), ('Detailing', 'Detailing'), ('Erection', 'Erection')], max_length=50, null=True),
        ),
    ]
