# Generated by Django 4.2.30 on 2026-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bidenquiry_scope_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Company', 'Company'), ('Optional', 'Optional')], default='Public', max_length=20)),
                ('timezone', models.CharField(choices=[('Asia/Kathmandu', 'Nepal (NPT)'), ('America/Chicago', 'US (CST)')], default='America/Chicago', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
                'unique_together': {('date', 'timezone')},
            },
        ),
    ]
