# Generated by Django 4.2.30 on 2026-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_add_holiday_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='timezone',
            field=models.CharField(choices=[('America/Chicago', 'US (CST)')], default='America/Chicago', max_length=50),
        ),
    ]
