

# Generated by Django 4.2.30 on 2026-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_alter_holiday_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidenquiry',
            name='scope_of_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
