# Generated by Django 4.2.30 on 2026-05-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('PLATE', 'Plate'), ('ANGLE', 'Angle'), ('STRUCTURAL', 'Structural')], default='PLATE', max_length=20)),
                ('process_type', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Production Priorities',
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPriorityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence_number', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rts_date', models.DateField(blank=True, null=True)),
                ('run_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_run_date', models.DateField(blank=True, null=True)),
                ('complete_run_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionpriority')),
            ],
        ),
        migrations.AddField(
            model_name='productionpriority',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='production.productionschedule'),
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=100)),
                ('sequence_number', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('rts_date', models.DateField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionschedule')),
            ],
        ),
    ]
