# Generated by Django 4.2.30 on 2026-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionpriorityitem",
            name="actual_bfa",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionpriorityitem",
            name="actual_ofa",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionpriorityitem",
            name="field_meas",
            field=models.BooleanField(default=False),
        ),
    ]
