# Generated by Django 4.2.30 on 2026-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_field_hours_structuralscheduleitem_actual_field_hours_and_more'),
        ('production', '0002_productionpriorityitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='production_schedules', to='projects.project'),
        ),
    ]
