# Generated by Django 4.2.30 on 2026-05-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_productionpriorityitem_actual_bfa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionpriorityitem",
            name="field_meas",
        ),
    ]
