# Generated by Django 4.2.30 on 2026-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionschedule_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpriorityitem',
            name='actual_bfa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionpriorityitem',
            name='actual_ofa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
