# Generated by Django 4.2.30 on 2026-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionpriorityitem_actual_bfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
