# Generated by Django 4.2.30 on 2026-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_machine_manpower_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='productivity_rate_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
