# Generated by Django 4.2.30 on 2026-05-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_manpower_productivity_rate_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='capacity_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
