# Generated by Django 4.2.30 on 2026-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_machine_capacity_per_day_machine_machine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='capacity_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capacity',
            name='machine_assigned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='capacity',
            name='manpower_assigned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
