# Generated by Django 4.2.30 on 2026-06-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_capacity_capacity_per_day_capacity_machine_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='manhours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='manpower',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
