# Generated by Django 4.2.30 on 2026-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_manpower_manhours_manpower_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='June', max_length=20),
        ),
    ]
