# Generated by Django 4.2.30 on 2026-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0011_manpower_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacity",
            name="capacity_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="capacity",
            name="capacity_per_year",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
