# Generated by Django 4.2.30 on 2026-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_capacity_capacity_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitem',
            name='production_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='production_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
