# Generated by Django 4.2.30 on 2026-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_capacity_capacity_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='months',
            field=models.TextField(blank=True, default='', help_text='Comma-separated months, e.g. January,February'),
        ),
    ]
