# Generated by Django 4.2.30 on 2026-06-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_capacity_months'),
        ('production', '0013_productionitem_production_end_date_and_more'),
    ]

    operations = [
    ]
