# Generated by Django 4.2.30 on 2026-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_merge_20260612_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpriorityitem',
            name='actual_rts_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
