# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('mh_per_pc', models.DecimalField(decimal_places=4, max_digits=6)),
                ('crane_picks_formula', models.CharField(default='qty', max_length=50)),
                ('input_unit', models.CharField(choices=[('pc', 'Piece'), ('lf', 'Linear Feet')], default='pc', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ErectionTakeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picks_per_day', models.IntegerField(default=35)),
                ('efficiency_factor', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erection_takeoff', to='projects.project')),
            ],
            options={
                'verbose_name': 'Erection Takeoff',
                'verbose_name_plural': 'Erection Takeoffs',
            },
        ),
        migrations.CreateModel(
            name='ErectionMemberLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('erection_takeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_lines', to='erection_takeoff.erectiontakeoff')),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_lines', to='erection_takeoff.membertype')),
            ],
            options={
                'ordering': ['sort_order', 'member_type__sort_order'],
                'unique_together': {('erection_takeoff', 'member_type')},
            },
        ),
    ]
