# Generated by Django 5.1.15 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erection_takeoff", "0002_seed_member_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="erectiontakeoff",
            name="equipment_rental",
            field=models.DecimalField(
                decimal_places=2, default="9000.00", max_digits=12
            ),
        ),
    ]
