# Generated by Django 5.1.15 on 2026-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erection_takeoff", "0003_erectiontakeoff_equipment_rental"),
    ]

    operations = [
        migrations.AddField(
            model_name="erectiontakeoff",
            name="crew_size",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="field_studs_qty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="foreman_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="perimeter_cable_qty",
            field=models.DecimalField(decimal_places=2, default=380, max_digits=10),
        ),
        migrations.AlterField(
            model_name="membertype",
            name="input_unit",
            field=models.CharField(
                choices=[
                    ("pc", "Piece"),
                    ("lf", "Linear Feet"),
                    ("sf", "Square Feet"),
                    ("each", "Each"),
                    ("set", "Set"),
                    ("hrs", "Hours"),
                ],
                default="pc",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membertype",
            name="mh_per_pc",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
