# Generated by Django 5.1.15 on 2026-06-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erection_takeoff", "0005_seed_missing_member_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="erectionmemberline",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterUniqueTogether(
            name="erectionmemberline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="crane_picks_formula",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="input_unit",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="erectionmemberline",
            name="mh_per_pc",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="erectionmemberline",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_lines",
                to="erection_takeoff.membertype",
            ),
        ),
        migrations.AddConstraint(
            model_name="erectionmemberline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member_type__isnull", False)),
                fields=("erection_takeoff", "member_type"),
                name="unique_member_type_per_takeoff",
            ),
        ),
    ]
