# Generated by Django 5.1.15 on 2026-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erection_takeoff", "0007_backfill_existing_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="erectiontakeoff",
            name="crane_rate",
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="field_studs_rate",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="foreman_rate",
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="ironworker_rate",
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="per_diem_rate",
            field=models.DecimalField(decimal_places=2, default=85.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="perimeter_cable_field_rate",
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="perimeter_cable_material_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="perimeter_cable_shop_rate",
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="travel_driver_rate",
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="travel_passenger_rate",
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="weeks_travel_driver_rate",
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="erectiontakeoff",
            name="weeks_travel_passenger_rate",
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
    ]
