# Generated by Django 4.2.30 on 2026-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erection_takeoff', '0009_rename_xbracing_member_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erectiontakeoff',
            name='perimeter_cable_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
