# Generated by Django 4.2.30 on 2026-06-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erection_takeoff', '0010_alter_erectiontakeoff_perimeter_cable_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erectiontakeoff',
            name='equipment_rental',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
