# Generated by Django 4.2.30 on 2026-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erection_takeoff', '0011_alter_erectiontakeoff_equipment_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='erectiontakeoff',
            name='freight_out_trucks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erectiontakeoff',
            name='joist_deck_tons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='erectiontakeoff',
            name='travel_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
